version: '3'
services:
  dev:
    build: .
    image: neolol-be-dev:latest
    working_dir: /usr/src/app
    network_mode: 'host'
    volumes:
      - /var/www/cdn.neolol.com:/var/www/cdn.neolol.com
    environment:
      - PORT=5001
      - DB_DATABASE=database
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_LOGGING=false
      - COOKIE_DOMAIN=example.com
      - COOKIE_SECURE=true
      - GOOGLE_CAPTCHA_V2_PRIVATE_KEY=key
      - GOOGLE_CAPTCHA_V3_PRIVATE_KEY=key
    command: bash -c "pm2-runtime start server.js"
    ports:
      - 5002:5002
  test:
    build: .
    image: neolol-be-dev:latest
    depends_on:
      - test_db
    working_dir: /
    volumes:
      - /var/www/cdn.neolol.com:/var/www/cdn.neolol.com
    environment:
      - PORT=5002
      - DB_HOST=test_db
      - DB_DATABASE=test
      - DB_PORT=3307
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_LOGGING=false
      - COOKIE_DOMAIN=example.com
      - COOKIE_SECURE=true
      - GOOGLE_CAPTCHA_V2_PRIVATE_KEY=key
      - GOOGLE_CAPTCHA_V3_PRIVATE_KEY=key
    command: bash -c "npx mocha app/test"
  test_db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_TCP_PORT=3307
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: