version: '3'
services:
  dev:
    build: .
    image: neolol-be-dev:latest
    working_dir: /
    network_mode: 'host'
    volumes:
      - /var/www/cdn.neolol.com:/var/www/cdn.neolol.com
    environment:
      - PORT=5001
      - DB_DATABASE=database
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_LOGGING=false
      - COOKIE_DOMAIN=example.com
      - COOKIE_SECURE=true
      - GOOGLE_CAPTCHA_V2_PRIVATE_KEY=key
      - GOOGLE_CAPTCHA_V3_PRIVATE_KEY=key
    command: bash -c "npx mocha app/test/test_comments.js"
    ports:
      - 5002:5002
    expose:
      - 3306
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
