exports.msg = {
  success:                { message: "SUCCESS" },
  missingData:            { message: "MISSING_DATA" },
  invalidPassword:        { message: "INVALID_PASSWORD" },
  alreadySignedIn:        { message: "ALREADY_SIGNED_IN" },
  badRequest:             { message: "BAD_REQUEST" },
  notAuthenticated:       { message: "NOT_AUTHENTICATED" },
  invalidIdentification:  { message: "INVALID_IDENTIFICATION" },
  invalidCredentials:     { message: "INVALID_CREDENTIALS" },
  captchaFailed:          { message: "CAPTCHA_FAILED" },
  notFound:               { message: "NOT_FOUND" },
  sessionExpired:         { message: "SESSION_EXPIRED" },
  invalidRefreshToken:    { message: "INVALID_REFRESH_TOKEN" },
  sameIp:                 { message: "SAME_IP" },
  signedOut:              { message: "SIGNED_OUT" },
  noFileUploaded:         { message: "NO_FILE_UPLOADED" },
  multipleFilesUploaded:  { message: "MULTIPLE_FILES_UPLOADED" },
  invalidMimeType:        { message: "INVALID_MIMETYPE" },
  fileTooLarge:           { message:  "FILE_TOO_LARGE" },
};

exports.code = {
  success:                200,
  created:                201,
  noContent:              204,
  missingData:            449,
  invalidPassword:        449,
  alreadySignedIn:        400,
  badRequest:             400,
  notAuthenticated:       401,
  invalidIdentification:  401,
  invalidCredentials:     401,
  captchaFailed:          400,
  notFound:               404,
  sessionExpired:         440,
  invalidRefreshToken:    400,
  sameIp:                 400,
  signedOut:              200,
  internalServerError:    500,
};
